# Generated by Django 3.2.3 on 2022-07-02 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220702_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='des',
        ),
    ]
