# Generated by Django 3.2.3 on 2022-07-02 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_category_des'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detail_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
