# Generated by Django 3.2.3 on 2022-07-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20220702_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(max_length=150, null=True, verbose_name='mobile'),
        ),
    ]
